[package]
name = "dbtp"
version = "0.2.1"
edition = "2021"
description = "A CLI for the dbt Cloud Platform API"
license = "Apache-2.0"
repository = "https://github.com/trouze/dbtp"
readme = "README.md"

[[bin]]
name = "dbtp"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive", "env"] }
reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
toml = "0.8"
tabled = { version = "0.17", features = ["std"] }
thiserror = "2"
directories = "6"
indicatif = "0.17"
chrono = { version = "0.4", features = ["serde"] }
base64 = "0.22"
arrow = { version = "53", default-features = false, features = ["ipc"] }
clap_complete = "4.6.0"

[profile.release]
strip = true
lto = true
codegen-units = 1
