query GetModelParents(
  $environmentId: BigInt!
  $modelsFilter: ModelAppliedFilter
  $first: Int
) {
  environment(id: $environmentId) {
    applied {
      models(filter: $modelsFilter, first: $first) {
        pageInfo {
          endCursor
        }
        edges {
          node {
            parents {
              ... on ExposureAppliedStateNestedNode {
                resourceType
                name
                description
              }
              ... on ExternalModelNode {
                resourceType
                description
                name
              }
              ... on MacroDefinitionNestedNode {
                resourceType
                name
                description
              }
              ... on MetricDefinitionNestedNode {
                resourceType
                name
                description
              }
              ... on ModelAppliedStateNestedNode {
                resourceType
                name
                description
              }
              ... on SavedQueryDefinitionNestedNode {
                resourceType
                name
                description
              }
              ... on SeedAppliedStateNestedNode {
                resourceType
                name
                description
              }
              ... on SemanticModelDefinitionNestedNode {
                resourceType
                name
                description
              }
              ... on SnapshotAppliedStateNestedNode {
                resourceType
                name
                description
              }
              ... on SourceAppliedStateNestedNode {
                resourceType
                sourceName
                uniqueId
                name
                description
              }
              ... on TestAppliedStateNestedNode {
                resourceType
                name
                description
              }
            }
          }
        }
      }
    }
  }
}
