query GetSources(
  $environmentId: BigInt!
  $sourcesFilter: SourceAppliedFilter
  $after: String
  $first: Int
) {
  environment(id: $environmentId) {
    applied {
      sources(filter: $sourcesFilter, after: $after, first: $first) {
        pageInfo {
          hasNextPage
          endCursor
        }
        edges {
          node {
            name
            uniqueId
            identifier
            description
            sourceName
            resourceType
            database
            schema
            freshness {
              maxLoadedAt
              maxLoadedAtTimeAgoInS
              freshnessStatus
            }
          }
        }
      }
    }
  }
}
