query GetModelHealth(
  $environmentId: BigInt!
  $modelsFilter: ModelAppliedFilter
  $first: Int
) {
  environment(id: $environmentId) {
    applied {
      models(filter: $modelsFilter, first: $first) {
        edges {
          node {
            name
            uniqueId
            executionInfo {
              lastRunGeneratedAt
              lastRunStatus
              executeCompletedAt
              executeStartedAt
            }
            tests {
              name
              description
              columnName
              testType
              executionInfo {
                lastRunGeneratedAt
                lastRunStatus
                executeCompletedAt
                executeStartedAt
              }
            }
            ancestors(types: [Model, Source, Seed, Snapshot]) {
              ... on ModelAppliedStateNestedNode {
                name
                uniqueId
                resourceType
                materializedType
                modelExecutionInfo: executionInfo {
                  lastRunStatus
                  executeCompletedAt
                }
              }
              ... on SnapshotAppliedStateNestedNode {
                name
                uniqueId
                resourceType
                snapshotExecutionInfo: executionInfo {
                  lastRunStatus
                  executeCompletedAt
                }
              }
              ... on SeedAppliedStateNestedNode {
                name
                uniqueId
                resourceType
                seedExecutionInfo: executionInfo {
                  lastRunStatus
                  executeCompletedAt
                }
              }
              ... on SourceAppliedStateNestedNode {
                sourceName
                name
                resourceType
                freshness {
                  maxLoadedAt
                  maxLoadedAtTimeAgoInS
                  freshnessStatus
                }
              }
            }
          }
        }
      }
    }
  }
}
